/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.nio.charset.StandardCharsets;
import org.apache.pulsar.client.api.ClientBuilder;
import org.apache.pulsar.client.api.Consumer;
import org.apache.pulsar.client.api.Message;
import org.apache.pulsar.client.api.PulsarClient;
import org.apache.pulsar.client.api.PulsarClientException;

public class App {
    public static void main(String[] args) {
        try {
            ClientBuilder clientBuilder = PulsarClient.builder();
            clientBuilder.serviceUrl("pulsar://localhost:6650");
            System.out.println("creating client");
            PulsarClient client = clientBuilder.build();
            Consumer<byte[]> consumer = client.newConsumer().topic("public/default/xyz").subscriptionName("scratch").subscribe();
            System.out.println("consumer created, waiting for message");
            Message<byte[]> receive = consumer.receive();
            System.out.println("received:" + new String(receive.getData(), StandardCharsets.UTF_8));
        } catch (PulsarClientException e) {
            throw new RuntimeException(e);
        }
    }
}
